home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('movies/', views.MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
]

koala/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers', 'actors')
        return qs

class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance Suggested'),
        (RATED_R, 'R - Restricted'),
    )

    title = models.CharField(max_length=140)
    plot = models.CharField(max_length=140)
    year = models.PositiveIntegerField()
    rating = models.PositiveIntegerField(
        choices=RATINGS,
        default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    director = models.ForeignKey(
        to='Person',
        null=True,
        on_delete=models.SET_NULL,
        related_name='directed',
        blank=True)
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True)
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True)
 
    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)

class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related('directed','writing_credits','role_set__movie')

class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died)
        return '{}, {} ({})'.format(
                self.last_name,
                self.first_name,
                self.born)

class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie', 'person', 'name')

home/views.py
# from django.shortcuts import render

# Create your views here.
from django.views.generic import (
    ListView, DetailView,
)
from home.models import Movie, Person

class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons()

class MovieList(ListView):
    model = Movie
    paginate_by = 10

class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()

class PersonList(ListView):
    model = Person
    paginate_by = 10

home/templates/home/movie_detail.html
{% extends 'base.html' %}

{% block title %} 
  {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1> {{ object }} </h1>
<p class="lead">
    {{ object.plot }}
</p>
{% endblock %}

{% block sidebar %}
<div>
This movie is rated:
    <span class="badge badge-primary">
        {{ object.get_rating_display }}
    </span>
</div>
{% endblock %}

home/templates/home/movie_list.html
{% extends 'base.html' %}

{% block title %} 
  All The Movies
{% endblock %}

{% block main %}
<ul>
    {% for movie in object_list %}
      <li>
            <a href="{% url 'home:MovieDetail' pk=movie.id %}">
                {{ movie }}
            </a>
      </li>
    {% endfor %}
</ul>

{% if is_paginated %}
    <nav>
        <ul class="pagination">
            <li class="page-item">
                <a href="{% url 'home:MovieList' %}?page=1" class="page-link">
                    First
                </a>    
            </li>
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="{% url 'home:MovieList' %}?page={{ page_obj.previous_page_number }}" class="page-link">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="page-item active">
                    <a href="{% url 'home:MovieList' %}?page={{ page_obj.number }}" class="page-link">
                        {{ page_obj.number }}
                    </a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="{% url 'home:MovieList' %}?page={{ page_obj.next_page_number }}" class="page-link">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="page-item">
                <a href="{% url 'home:MovieList' %}?page=last" class="page-link">
                    Last
                </a>    
            </li>
        </ul>
    </nav>
{% endif %}
{% endblock %}    

home/templates/home/person_detail.html
{% extends 'base.html' %}

{% block title %} 
  {{ object.first_name }} 
  {{ object.last_name }}
{% endblock %}

{% block main %}
<h1> {{ object }} </h1>
<h2>Actor</h2>
<ul>
    {% for role in object.role_set.all %}
    <li>
        <a href="{% url 'home:MovieDetails' role.movie.id %}">
            {{ role.movie }}
        </a>:
        {{ role.name }}
    </li>
    {% endfor %}
</ul>
<h2>Writer</h2>
<ul>
    {% for movie in object.writing_credits.all %}
    <li>
        <a href="{% url 'home:MovieDetail' movie.id %}">
            {{ movie }}
        </a>
    </li>
    {% endfor%}
</ul>
{% endblock %}
<h2>Director</h2>
<ul>
    {% for movie in object.directed.all %}
    <li>
        <a href="{% url 'home:MovieDetail' movie.id %}">
            {{ movie }}
        </a>
    </li>
    {% endfor%}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        >
        <link rel="stylesheet" 
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
              crossorigin="anonymous">
        <title>
            {% block title %} MyMDB {% endblock %}
        </title>
        <style>
            .mymdb-masthead {
                background-color: #EEEEEE;
                margin-bottom: 1em;
            }
        </style>
    </head>
    <body>
    <div class="mymdb-masthead">
        <div class="container">
            <nav class="nav">
                <div class="navbar-brand">MyMDB</div>
                <a 
                    class="nav-link"
                    href="{% url 'home:MovieList' %}"
                >
                    Movies 
                </a>
            </nav>
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <div class="col-sm-8 mymdb-main">
                {% block main %}{% endblock %}
            </div>
            <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
                {% block sidebar %}{% endblock %}
            </div>
        </div>
    </div>
    </body>
</html>